In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' ,'4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [5]:
#For list_
for i in list_:
    print(i)

1
2
3
4
5


In [6]:
#For array_list:
for i in array_list:
    print(i)

1
2
3
4
5


### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [7]:
array_list = np.array(object = list_, dtype = int)

In [8]:
array_list

array([1, 2, 3, 4, 5])

In [9]:
list_

['1', '2', '3', '4', '5']

In [10]:
#For list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
#For array_list:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [13]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
num_array.shape #Gives matrik row column form  shape

(2, 3)

In [15]:
num_array.size #Gives total elements in num_array

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
arr=np.zeros((3,3))

In [17]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
arr=np.eye(5)

In [19]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])